apiVersion: v1
kind: Pod
metadata:
  name: unsigned-image-test
spec:
  restartPolicy: Never
  containers:
    - name: app
      image: 711387135481.dkr.ecr.us-east-1.amazonaws.com/bootcamp-api:unsigned-test
