apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::711387135481:role/bootcamp-eks-nodes
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-24T21:52:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1001"
  uid: a4420472-da2b-493f-b936-e043e2ca652b
