apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: bootcamp-excess-media
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootcamp-frontend
  namespace: bootcamp-excess-media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bootcamp-frontend
  template:
    metadata:
      labels:
        app: bootcamp-frontend
    spec:
      serviceAccountName: frontend
      containers:
        - name: curl
          image: curlimages/curl:8.8.0
          imagePullPolicy: IfNotPresent
          command: ["sleep", "infinity"]
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
