admissionWebhooks:
  certManager:
    enabled: false
  autoGenerateCert:
    enabled: true

manager:
  collectorImage:
    repository: otel/opentelemetry-collector-contrib
    tag: 0.97.0
  resources:
    requests: { cpu: 100m, memory: 256Mi }
    limits:   { cpu: 500m, memory: 512Mi }
