image:
  registry: docker.io
  repository: falcosecurity/falco
  tag: 0.44.0

driver:
  enabled: true
  kind: modern_ebpf
  modernEbpf:
    bufSizePreset: 4

collectors:
  enabled: true
  kubernetes:
    enabled: true
    collectorHostname: ""
    collectorPort: ""

falcoctl:
  artifact:
    install:
      enabled: true
      refs:
        - falco-rules:3
        - falco-incubating-rules:3
    follow:
      enabled: true
      refs:
        - falco-rules:3

falco:
  rules_files:
    - /etc/falco/falco_rules.yaml
    - /etc/falco/falco_rules.local.yaml
    - /etc/falco/k8s_audit_rules.yaml
    - /etc/falco/rules.d
  json_output: true
  json_include_output_property: true
  log_stderr: true
  log_syslog: false
  priority: notice
  buffered_outputs: false
  syscall_event_drops:
    actions: [log, alert]
    rate: 0.03333
    max_burst: 10
  http_output:
    enabled: true
    url: http://falco-falcosidekick.falco.svc.cluster.local:2801

falcosidekick:
  enabled: true
  replicaCount: 2
  image:
    tag: 2.31.1
  config:
    alertmanager:
      hostport: http://alertmanager-operated.observability.svc.cluster.local:9093
      expireafter: "30"
      extralabels: severity:high,source:falco
      minimumpriority: notice
    prometheus:
      extralabels: cluster:bootcamp-eks
  webui:
    enabled: true
    replicaCount: 1

serviceMonitor:
  enabled: true

resources:
  requests: { cpu: 100m, memory: 512Mi }
  limits: { cpu: "1", memory: 1Gi }
