apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bootcamp-api
  namespace: bootcamp
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: bootcamp-api
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
  data:
    - secretKey: DB_URL
      remoteRef:
        key: bootcamp/api
        property: DB_URL
    - secretKey: REDIS_URL
      remoteRef:
        key: bootcamp/api
        property: REDIS_URL
    - secretKey: JWT_SIGNING_KEY
      remoteRef:
        key: bootcamp/api
        property: JWT_SIGNING_KEY
